project_id = "nplhsonknhufztsbdyvh"

[functions.ai-planner]
verify_jwt = true

[functions.send-package-email]
verify_jwt = true

[functions.send-sos-alert]
verify_jwt = true

[functions.send-daily-reminder]
verify_jwt = true

[functions.extract-itinerary]
verify_jwt = true
